#pragma once
#include <pebble.h>

#define SETTINGS_KEY 148

typedef struct ClaySettings {
  int SecondsVisibleTime;
  bool EnableDate;
  bool EnableBattery;
  bool EnableBatteryLine;
  char VibeMode[4];
  char DateFormat[4];
  bool showMinorTick;
  bool showMajorTick;
  int MinuteCentreSize;
  int HourCentreSize;
  int InnerCentreSize;
  int SecondOuterCentreSize;
  int SecondInnerCentreSize;
  int MinuteHandThickness;
  int HourHandThickness;
  int BackSize;
  int BackLen;
  char BWThemeSelect[4];
  char ThemeSelect[4];
  GColor BackgroundColor1;
  GColor MinuteHandShadowColor;
  GColor MinorTickColor;
  GColor MajorTickColor;
  GColor DateColor;
  GColor BWDateColor;
  GColor HourDigitsColor;
  GColor MinutesHandColor;
  GColor MonthHandColor;
  GColor BWMonthHandColor;
  GColor SecondsHandColor;
  GColor BWSecondsHandColor;
  GColor BatteryLineColor;
  GColor BWBackgroundColor1;
  GColor BWMinuteHandShadowColor;
  GColor BWMinHandBatLineColor;
  GColor BWHourDigitsColor;
  GColor BWMajorTickColor;
  GColor BTQTColor;
  GColor BWBTQTColor;
  GColor SubDialColor;
  GColor BWSubDialColor;
  bool BWShadowOn;
  bool ShadowOn;
  bool ForegroundShape;
  bool UseWeather;
  int UpSlider;
  //int WeatherUnit;
  char tempstring[6];
  char temphistring[12];
  char iconnowstring[4];
  bool RainSoon;
  int WBGTLevel; // 0 = none, 1 = Yellow, 2 = Red, 3 = Black
  bool AlwaysShowSubDial;
  bool Roman;
  bool showremoteAMPM;
  int RemoteTimeOffsetMinutes;
  //bool tz_mode;
  //int tz_id;
  int tz_offset;
  //char tz_code[7];
  int SubDialChoice;
  bool SmoothSweep;
  char DateLanguage[6];
  bool RefreshWeatherOnLaunch;
} __attribute__((__packed__)) ClaySettings;